FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY drizzle.config.ts ./
COPY lib ./lib
COPY scripts ./scripts

CMD ["sh", "-c", "npm run db:push && npm run bootstrap"]
