#!/usr/bin/env bash
# Interactive wizard — generates .env without manual editing

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=common.sh
source "$SCRIPT_DIR/common.sh"

prompt() {
  local label=$1 default=${2:-}
  local var
  if [[ -n "$default" ]]; then
    read -rp "$label [$default]: " var
    var="${var:-$default}"
  else
    read -rp "$label: " var
  fi
  echo "$var"
}

prompt_secret() {
  local label=$1
  local var
  read -rsp "$label: " var
  echo
  echo "$var"
}

run_wizard() {
  print_banner
  echo "Wizard akan membuat file .env otomatis."
  echo "Tekan Enter untuk nilai default (jika ada)."
  echo

  DEPLOY_DOMAIN="$(prompt "Domain (contoh: storage.example.com)")"
  DEPLOY_DOMAIN="${DEPLOY_DOMAIN#https://}"
  DEPLOY_DOMAIN="${DEPLOY_DOMAIN#http://}"
  DEPLOY_DOMAIN="${DEPLOY_DOMAIN%%/*}"

  CERTBOT_EMAIL="$(prompt "Email admin (Let's Encrypt notifications)" "admin@${DEPLOY_DOMAIN}")"

  echo
  echo "--- Database (Neon PostgreSQL) ---"
  DATABASE_URL="$(prompt "DATABASE_URL (paste dari Neon dashboard)")"

  echo
  echo "--- Cloudflare R2 ---"
  R2_ACCOUNT_ID="$(prompt "R2 Account ID")"
  R2_ACCESS_KEY_ID="$(prompt "R2 Access Key ID")"
  R2_SECRET_ACCESS_KEY="$(prompt_secret "R2 Secret Access Key")"
  R2_BUCKET_NAME="$(prompt "R2 Bucket name" "storage-by-afr")"
  R2_PUBLIC_URL="$(prompt "R2 Public URL (https://pub-xxx.r2.dev)")"

  echo
  echo "--- Admin pertama ---"
  MASTER_USERNAME="$(prompt "Admin username" "ByAFR")"
  MASTER_PASSWORD="$(prompt_secret "Admin password (min 10 karakter)")"

  if [[ ${#MASTER_PASSWORD} -lt 10 ]]; then
    die "Password admin minimal 10 karakter."
  fi

  if command -v openssl >/dev/null 2>&1; then
    SESSION_SECRET="$(openssl rand -hex 32)"
  else
    SESSION_SECRET="$(head -c 48 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 64)"
  fi

  NEXT_PUBLIC_APP_URL="https://${DEPLOY_DOMAIN}"
  COOKIE_SECURE=true
  HSTS_ENABLED=true
  REDIS_URL=redis://redis:6379
  REDIS_DISABLED=false
  NODE_ENV=production

  mkdir -p "$ROOT/.deploy"
  echo "$DEPLOY_DOMAIN" > "$DOMAIN_FILE"

  cat > "$ENV_FILE" <<'ENVEOF'
# Generated by Storage ByAFR install wizard
ENVEOF

  write_env() {
    local key=$1
    local val=$2
    val="${val//\\/\\\\}"
    val="${val//\"/\\\"}"
    printf '%s="%s"\n' "$key" "$val" >> "$ENV_FILE"
  }

  write_env NODE_ENV production
  write_env DEPLOY_DOMAIN "$DEPLOY_DOMAIN"
  write_env CERTBOT_EMAIL "$CERTBOT_EMAIL"
  write_env DATABASE_URL "$DATABASE_URL"
  write_env R2_ACCOUNT_ID "$R2_ACCOUNT_ID"
  write_env R2_ACCESS_KEY_ID "$R2_ACCESS_KEY_ID"
  write_env R2_SECRET_ACCESS_KEY "$R2_SECRET_ACCESS_KEY"
  write_env R2_BUCKET_NAME "$R2_BUCKET_NAME"
  write_env R2_PUBLIC_URL "$R2_PUBLIC_URL"
  write_env SESSION_SECRET "$SESSION_SECRET"
  write_env MASTER_USERNAME "$MASTER_USERNAME"
  write_env MASTER_PASSWORD "$MASTER_PASSWORD"
  write_env NEXT_PUBLIC_APP_URL "$NEXT_PUBLIC_APP_URL"
  write_env COOKIE_SECURE true
  write_env HSTS_ENABLED true
  write_env REDIS_URL redis://redis:6379
  write_env REDIS_DISABLED false
  write_env MAX_FILE_SIZE_BYTES 5368709120
  write_env UPLOAD_URL_EXPIRY_SECONDS 900
  write_env DOWNLOAD_URL_EXPIRY_SECONDS 60
  write_env PREVIEW_URL_EXPIRY_SECONDS 3600
  write_env RATE_LIMIT_LOGIN_MAX 5
  write_env RATE_LIMIT_LOGIN_WINDOW_MS 900000
  write_env RATE_LIMIT_LOGIN_IP_MAX 30
  write_env SESSION_INACTIVITY_MS 1800000

  echo "# Generated at $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> "$ENV_FILE"

  save_deploy_state
  ok "File .env dibuat di $ENV_FILE"
  echo
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  run_wizard
fi
