#!/usr/bin/env bash
# Interactive wizard — generates .env without manual editing

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=common.sh
source "$SCRIPT_DIR/common.sh"

prompt_into() {
  local label=$1
  local -n _out=$2
  local default=${3:-}
  if [[ -n "$default" ]]; then
    read -rp "$label [$default]: " _out </dev/tty
    _out="${_out:-$default}"
  else
    read -rp "$label: " _out </dev/tty
  fi
  _out="$(sanitize_env_value "$_out")"
}

prompt_secret_into() {
  local label=$1
  local -n _out=$2
  echo "  (input tersembunyi — ketik lalu Enter)" >&2
  read -rsp "$label: " _out </dev/tty
  echo >&2
  _out="$(sanitize_env_value "$_out")"
}

require_nonempty() {
  local label=$1
  local -n _val=$2
  while [[ -z "$_val" ]]; do
    warn "$label wajib diisi."
    prompt_into "$label" _val
  done
}

require_secret_nonempty() {
  local label=$1
  local -n _val=$2
  while [[ -z "$_val" ]]; do
    warn "$label wajib diisi."
    prompt_secret_into "$label" _val
  done
}

run_wizard() {
  print_banner
  echo "Wizard akan membuat file .env otomatis."
  echo "Tekan Enter untuk nilai default (jika ada)."
  echo

  prompt_into "Domain (contoh: storage.example.com)" DEPLOY_DOMAIN
  DEPLOY_DOMAIN="${DEPLOY_DOMAIN#https://}"
  DEPLOY_DOMAIN="${DEPLOY_DOMAIN#http://}"
  DEPLOY_DOMAIN="${DEPLOY_DOMAIN%%/*}"

  prompt_into "Email admin (Let's Encrypt notifications)" CERTBOT_EMAIL "admin@${DEPLOY_DOMAIN}"

  echo
  echo "--- Database (Neon PostgreSQL) ---"
  prompt_into "DATABASE_URL (paste dari Neon dashboard)" DATABASE_URL
  require_nonempty "DATABASE_URL" DATABASE_URL

  echo
  echo "--- Cloudflare R2 ---"
  prompt_into "R2 Account ID" R2_ACCOUNT_ID
  require_nonempty "R2 Account ID" R2_ACCOUNT_ID
  prompt_into "R2 Access Key ID" R2_ACCESS_KEY_ID
  require_nonempty "R2 Access Key ID" R2_ACCESS_KEY_ID
  prompt_secret_into "R2 Secret Access Key" R2_SECRET_ACCESS_KEY
  require_secret_nonempty "R2 Secret Access Key" R2_SECRET_ACCESS_KEY
  prompt_into "R2 Bucket name" R2_BUCKET_NAME "storage-by-afr"
  prompt_into "R2 Public URL (https://pub-xxx.r2.dev)" R2_PUBLIC_URL
  require_nonempty "R2 Public URL" R2_PUBLIC_URL

  echo
  echo "--- Admin pertama ---"
  prompt_into "Admin username" MASTER_USERNAME "ByAFR"
  prompt_secret_into "Admin password (min 10 karakter)" MASTER_PASSWORD
  while [[ ${#MASTER_PASSWORD} -lt 10 ]]; do
    warn "Password admin minimal 10 karakter."
    prompt_secret_into "Admin password (min 10 karakter)" MASTER_PASSWORD
  done

  if command -v openssl >/dev/null 2>&1; then
    SESSION_SECRET="$(openssl rand -hex 32)"
  else
    SESSION_SECRET="$(head -c 48 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 64)"
  fi

  NEXT_PUBLIC_APP_URL="https://${DEPLOY_DOMAIN}"
  COOKIE_SECURE=true
  HSTS_ENABLED=true
  REDIS_URL=redis://redis:6379
  REDIS_DISABLED=false
  NODE_ENV=production

  mkdir -p "$ROOT/.deploy"
  echo "$DEPLOY_DOMAIN" > "$DOMAIN_FILE"

  cat > "$ENV_FILE" <<'ENVEOF'
# Generated by Storage ByAFR install wizard
ENVEOF

  env_set_line NODE_ENV production
  env_set_line DEPLOY_DOMAIN "$DEPLOY_DOMAIN"
  env_set_line CERTBOT_EMAIL "$CERTBOT_EMAIL"
  env_set_line DATABASE_URL "$DATABASE_URL"
  env_set_line R2_ACCOUNT_ID "$R2_ACCOUNT_ID"
  env_set_line R2_ACCESS_KEY_ID "$R2_ACCESS_KEY_ID"
  env_set_line R2_SECRET_ACCESS_KEY "$R2_SECRET_ACCESS_KEY"
  env_set_line R2_BUCKET_NAME "$R2_BUCKET_NAME"
  env_set_line R2_PUBLIC_URL "$R2_PUBLIC_URL"
  env_set_line SESSION_SECRET "$SESSION_SECRET"
  env_set_line MASTER_USERNAME "$MASTER_USERNAME"
  env_set_line MASTER_PASSWORD "$MASTER_PASSWORD"
  env_set_line NEXT_PUBLIC_APP_URL "$NEXT_PUBLIC_APP_URL"
  env_set_line COOKIE_SECURE true
  env_set_line HSTS_ENABLED true
  env_set_line REDIS_URL redis://redis:6379
  env_set_line REDIS_DISABLED false
  env_set_line MAX_FILE_SIZE_BYTES 5368709120
  env_set_line UPLOAD_URL_EXPIRY_SECONDS 900
  env_set_line DOWNLOAD_URL_EXPIRY_SECONDS 60
  env_set_line PREVIEW_URL_EXPIRY_SECONDS 3600
  env_set_line RATE_LIMIT_LOGIN_MAX 5
  env_set_line RATE_LIMIT_LOGIN_WINDOW_MS 900000
  env_set_line RATE_LIMIT_LOGIN_IP_MAX 30
  env_set_line SESSION_INACTIVITY_MS 1800000

  echo "# Generated at $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> "$ENV_FILE"

  save_deploy_state
  ok "File .env dibuat di $ENV_FILE"
  echo
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  run_wizard
fi
