FROM node:20-alpine

RUN apk add --no-cache ffmpeg

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --omit=dev
RUN npm install tsx sharp drizzle-orm postgres @aws-sdk/client-s3 @neondatabase/serverless ioredis bullmq @node-rs/argon2

COPY lib ./lib
COPY workers ./workers
COPY drizzle.config.ts ./

CMD ["npx", "tsx", "workers/index.ts"]
